#used to generate ordering related questions through LLM and calculate result. 
import os
import re
import ast
import random
from supabase import create_client, Client #pip install supabase
from dotenv import load_dotenv   #pip install dotenv
from ollama import chat, generate
from ollama import ChatResponse
import json
from flask import Flask, jsonify
from flask_cors import CORS #pip install flask-cors
import sympy as sp #pip install sympy
from sympy import symbols, Eq, solve, sympify, Integer
from sympy.parsing.sympy_parser import (
    parse_expr,
    standard_transformations,
    implicit_multiplication_application
) #treat 2x as 2*x for sympy parsing

# Enable implicit multiplication (2x → 2*x)
transformations = (standard_transformations + (implicit_multiplication_application,))
def to_native(value): 
    if isinstance(value, Integer): 
        return int(value) 
    return value
def normalize(value):
    try: 
        return float(sympify(value))
    except: 
        raise ValueError(f"Invalid value: {value}")
def extract_json(text):
    match = re.search(r"\{.*?\}", text, re.DOTALL)
    return match.group() if match else None

ordering_prompt = f"""
You are to provide a Math question suitable for 6th–8th grade students. The response must be in JSON format. 
The Question Text, Question Topic, and Variables will be displayed. The Question Topic will be "ordering".

Ordering example question: "Order from least to greatest: 3/6, 0.6, 2/3, 0.75". The question text should display the direction
(least_to_greatest or greatest_to_least) as well as every value to be ordered. There should not be equivalent values, for example 0.5 and 1/2 should not 
both be values for a single question. All values should be numeric, with an emphasis on unequivalent decimals and rational values. Values may go to two decimal places.
Return ONLY valid JSON with no text before or after the JSON object.

The JSON must follow this exact structure:

{{
  "question_text": "Order from least to greatest: 3/6, 0.6, 2/3, 0.75",
  "question_topic": "ordering",
  "direction": "least_to_greatest", 
  "values": ["3/4", "0.6", "2/3", "0.75"]
}}

Rules:
- Use ONLY double quotes for all strings.
- The JSON object must contain the keys "question_text", "question_topic", "direction", and "values".
- "values" must be a list of strings.
- Do NOT include any characters outside the JSON object.
"""

#order values generated by LLM by least to greatest or greatest to least 
def solve_ordering(values, direction="least_to_greatest"):
    normalized = [(v, normalize(v)) for v in values] #treat strings from JSON  as floats

    sorted_vals = sorted(normalized, 
                         key=lambda x:x[1],
                         reverse=(direction=="greatest_to_least"))

    return [v[0] for v in sorted_vals]



def generate_ordering_question(global_questions, prev_questions, max_retries=3):
    for attempt in range(max_retries):
        if attempt > 0:
            prompt = ordering_prompt + "\nREMEMBER: ONLY RETURN VALID JSON. NO EXTRA TEXT."
        else:
            prompt = ordering_prompt


        prompt += (
            "\nPreviously generated questions:\n"
            + "\n".join(q["text"] for q in prev_questions)
            + "\n\nRecent global questions:\n"
            + "\n".join(q["text"] for q in global_questions)
            + "\n\nDO NOT generate a question matching any of the above. Use different wording and numerical values."
        )
            
        response = generate(
            model="llama3.1:8b",
            prompt=prompt,
            options={
                "temperature": 1.1, #more creativity
                "top_p": 0.95, #more diversity
                "top_k": 100 #broader token sampling.
            }
        )

        raw = extract_json(response.response)

        if not raw:
            print(f"[Attempt {attempt+1}] No JSON found")
            print(response.response)
            continue

        try:
            question_data = json.loads(raw)
        except Exception as e:
            print(f"[Attempt {attempt+1}] JSON parse failed:", e)
            print(response.response)
            continue

        # Validate required keys
        required_keys = ["values", "question_text", "direction"]
        if not all(k in question_data for k in required_keys):
            print(f"[Attempt {attempt+1}] Missing keys:", question_data)
            continue

        # If we reach here → SUCCESS
        break

    else:
        # All retries failed
        raise ValueError("Failed to generate valid JSON after retries")
    
    
    if question_data: 
        solution = solve_ordering(question_data["values"], question_data["direction"])

    for attempt in range(max_retries):
        incorrect_solution_prompt = f"""
        Generate three incorrect numerical answer options for a math problem.
        Question:
        {question_data["question_text"]}
        Correct Answer:
        {solution}

        Rules:
        - NO additional text, characters, or symbols should accompany this response. Response should strictly include JSON formatted data.
        - The answers must NOT equal or simplify to {solution}. However, each incorrect answer should contain each individual value from the solution.
        - Each answer should be an array of values derived from the solution. No other numbers should be involved in an answer.
        - The number of values in each incorrect answer should be the same as the number of values in the correct solution.
        - Return JSON format: each array value of incorrect_answers should be a separate incorrect answer
        {{
        "incorrect_answers": [
            ["x", "x", "x"],
            ["x", "x", "x"],
            ["x", "x", "x"]
        ]
        }}
        """

        if (solution != None):
            answer_response = generate(model="llama3.1:8b",
                                    prompt=incorrect_solution_prompt,
                                    options = {"temperature": 0.4,
                                                "top_p": 0.9,
                                                "top_k": 40}) #slightly less randomness, 
        if attempt > 0:
            incorrect_solution_prompt += "\nREMEMBER: ONLY RETURN VALID JSON. NO EXTRA TEXT."

        raw = extract_json(answer_response.response)

        if not raw:
            print(f"[Attempt {attempt+1}] No JSON found")
            print(answer_response.response)
            continue

        try:
            answer_data = json.loads(raw)
        except Exception as e:
            print(f"[Attempt {attempt+1}] JSON parse failed:", e)
            print(answer_response.response)
            continue

        # Validate required keys
        required_keys = ["incorrect_answers"]
        if not all(k in answer_data for k in required_keys):
            print(f"[Attempt {attempt+1}] Missing keys:", answer_data)
            continue

        # If we reach here → SUCCESS
        break

    else:
        # All retries failed
        raise ValueError("Failed to generate valid JSON after retries")

    #combining generated incorrect responses with correct solution. 
    incorrect_data = answer_data
    #parsed_incorrect = [ast.literal_eval(ans) for ans in incorrect_data["incorrect_answers"]]

    #answers = parsed_incorrect + [solution]

    answers = incorrect_data["incorrect_answers"] + [solution]
    random.shuffle(answers)

    #Build final JSON
    return {
        "question_text": question_data["question_text"],
        "answer_options": answers,
        "correct_answer": solution
    }

#ORDERING ISSUES: generated solution is in different format from calculated solution. Generated solutions don't include every value needed.


# app= Flask(__name__)
# CORS(app)
# @app.route("/")
# def display_question():
#     return jsonify(generate_ordering_question())